import type {
  Vendor,
  Category,
  Review,
  Testimonial,
  ServiceItem,
  PortfolioItem,
  TimeSlot,
  BookingPackage,
} from '@/lib/types/vendor'

// ─────────────────────────────────────────────────────────────────────────────
// lib/data.ts — backwards-compat shim.
// All hardcoded portal data has been migrated to backend hooks under
// lib/content/*. Types live in lib/types/vendor.ts; formatINR/getPriceRange
// in lib/format.ts.
//
// Only the `vendors` array below is still kept — it's referenced by the
// wedding-only `/planner` route which Phase 4 will replace with a
// <ComingSoonPage />. Once that lands, this whole file collapses to just the
// re-export shim.
// ─────────────────────────────────────────────────────────────────────────────

export type {
  Vendor,
  Category,
  Review,
  Testimonial,
  ServiceItem,
  PortfolioItem,
  TimeSlot,
  BookingPackage,
}
export { formatINR, getPriceRange } from '@/lib/format'

// ===== VENDORS =====
// Legacy mock entries below predate the `vendorType / coverImageUrl / logoUrl`
// additions to `Vendor` (these came in with the discovery/portal merge). The
// planner is the only remaining consumer (a `.filter(...).length` count for
// the budget slider) — it never reads those three fields. We keep the literal
// verbatim and inject `null` defaults at the export boundary so the array is
// `Vendor[]`-compatible without touching every entry.
type LegacyMockVendor = Omit<Vendor, 'vendorType' | 'coverImageUrl' | 'logoUrl'>;
const _vendorsLegacy: LegacyMockVendor[] = [
  // --- Mehndi Artists ---
  {
    id: "v-1",
    name: "Rani Mehndi Arts",
    slug: "rani-mehndi-arts",
    category: "Mehndi Artist",
    categorySlug: "mehndi-artist",
    subcategory: "Bridal Mehndi",
    description: "Award-winning bridal mehndi artist with intricate Rajasthani and Arabic designs.",
    longDescription: "Rani Mehndi Arts has been the go-to name in bridal mehndi for over 12 years. Specializing in intricate Rajasthani and Arabic designs, we bring a fusion of traditional motifs and modern aesthetics to every bride's hands. Our organic mehndi paste ensures rich, dark color that lasts. We offer personalized design consultations and travel across India for destination weddings.",
    city: "Jaipur",
    area: "Malviya Nagar",
    priceMin: 5000,
    priceMax: 25000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 342,
    tags: ["Bridal", "Rajasthani", "Arabic", "Organic Mehndi"],
    featured: true,
    verified: true,
    experience: 12,
    bookings: 890,
    availability: true,
  },
  {
    id: "v-2",
    name: "Zainab Henna Studio",
    slug: "zainab-henna-studio",
    category: "Mehndi Artist",
    categorySlug: "mehndi-artist",
    subcategory: "Arabic Mehndi",
    description: "Elegant Arabic mehndi designs with a contemporary twist.",
    longDescription: "Zainab Henna Studio is known for its contemporary Arabic mehndi designs that blend elegance with artistry. With over 8 years in the industry, Zainab has adorned the hands of thousands of brides across Mumbai and beyond. Her signature flowing patterns and use of negative space make each design a work of art.",
    city: "Mumbai",
    area: "Bandra West",
    priceMin: 8000,
    priceMax: 35000,
    priceUnit: "per event",
    rating: 4.8,
    reviewCount: 218,
    tags: ["Arabic", "Contemporary", "Bridal", "Guest Mehndi"],
    featured: true,
    verified: true,
    experience: 8,
    bookings: 560,
    availability: true,
  },
  {
    id: "v-3",
    name: "Lakshmi Mehndi Wali",
    slug: "lakshmi-mehndi-wali",
    category: "Mehndi Artist",
    categorySlug: "mehndi-artist",
    subcategory: "Traditional Mehndi",
    description: "Traditional North Indian mehndi with dulha-dulhan motifs.",
    longDescription: "Lakshmi Mehndi Wali carries forward a family tradition of three generations in the art of mehndi. Specializing in traditional North Indian bridal designs with intricate dulha-dulhan motifs, peacocks, and kalash patterns. Known for deep, dark staining mehndi and personalized storytelling designs.",
    city: "Delhi",
    area: "Chandni Chowk",
    priceMin: 3000,
    priceMax: 15000,
    priceUnit: "per event",
    rating: 4.7,
    reviewCount: 456,
    tags: ["Traditional", "North Indian", "Dulhan Design", "Family Mehndi"],
    featured: false,
    verified: true,
    experience: 20,
    bookings: 1200,
    availability: true,
  },
  {
    id: "v-4",
    name: "Priya Mehendi Creations",
    slug: "priya-mehendi-creations",
    category: "Mehndi Artist",
    categorySlug: "mehndi-artist",
    subcategory: "Fusion Mehndi",
    description: "Unique fusion mehndi blending Indo-Western patterns.",
    longDescription: "Priya Mehendi Creations offers a unique blend of Indian and Western design elements. Perfect for the modern bride who wants something different. Priya specializes in minimalist bridal mehndi, geometric patterns, and personalized portrait mehndi. She also offers glitter and white mehndi options for the engagement and sangeet.",
    city: "Bangalore",
    area: "Koramangala",
    priceMin: 6000,
    priceMax: 30000,
    priceUnit: "per event",
    rating: 4.6,
    reviewCount: 167,
    tags: ["Fusion", "Modern", "Minimalist", "Portrait Mehndi"],
    featured: false,
    verified: true,
    experience: 6,
    bookings: 340,
    availability: true,
  },
  {
    id: "v-5",
    name: "Mehndi by Saba",
    slug: "mehndi-by-saba",
    category: "Mehndi Artist",
    categorySlug: "mehndi-artist",
    subcategory: "Bridal Mehndi",
    description: "Celebrity mehndi artist known for elaborate full-hand designs.",
    longDescription: "Saba is one of Hyderabad's most sought-after mehndi artists, having worked with several celebrity brides and Bollywood personalities. Her signature elaborate full-hand designs feature incredibly fine details and take 4-6 hours for the bride alone. She guarantees the deepest, richest mehndi color using her proprietary organic paste recipe.",
    city: "Hyderabad",
    area: "Jubilee Hills",
    priceMin: 15000,
    priceMax: 60000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 289,
    tags: ["Celebrity", "Premium", "Full Hand", "Organic"],
    featured: true,
    verified: true,
    experience: 15,
    bookings: 720,
    availability: true,
  },
  {
    id: "v-6",
    name: "Kavita's Mehndi Magic",
    slug: "kavitas-mehndi-magic",
    category: "Mehndi Artist",
    categorySlug: "mehndi-artist",
    subcategory: "Budget Mehndi",
    description: "Affordable and beautiful mehndi for all occasions.",
    longDescription: "Kavita's Mehndi Magic offers beautiful, quality mehndi designs at affordable prices. Perfect for families on a budget who don't want to compromise on beauty. Kavita and her team of 5 artists can handle large guest mehndi sessions efficiently. Package deals available for bride + family combos.",
    city: "Lucknow",
    area: "Hazratganj",
    priceMin: 2000,
    priceMax: 10000,
    priceUnit: "per event",
    rating: 4.4,
    reviewCount: 312,
    tags: ["Affordable", "Team Available", "Guest Mehndi", "Package Deals"],
    featured: false,
    verified: true,
    experience: 10,
    bookings: 950,
    availability: true,
  },

  // --- Tent & Decoration ---
  {
    id: "v-7",
    name: "Royal Tent House",
    slug: "royal-tent-house",
    category: "Tent & Decoration",
    categorySlug: "tent-decoration",
    subcategory: "Full Decoration",
    description: "Grand wedding decorations with royal themes and luxury setups.",
    longDescription: "Royal Tent House has been creating breathtaking wedding setups for 25 years in Delhi. From elaborate mandap decorations to grand entrance arches, flower walls, and theme-based stage designs, they handle everything. Specializing in royal Rajasthani themes, floral installations, and LED lighting systems that transform any venue into a palace.",
    city: "Delhi",
    area: "Karol Bagh",
    priceMin: 50000,
    priceMax: 500000,
    priceUnit: "per event",
    rating: 4.8,
    reviewCount: 534,
    tags: ["Royal Theme", "Mandap", "Floral", "LED Lighting"],
    featured: true,
    verified: true,
    experience: 25,
    bookings: 2100,
    availability: true,
  },
  {
    id: "v-8",
    name: "Shubh Decorators",
    slug: "shubh-decorators",
    category: "Tent & Decoration",
    categorySlug: "tent-decoration",
    subcategory: "Stage Decoration",
    description: "Modern stage and mandap designs with fresh flower arrangements.",
    longDescription: "Shubh Decorators specialize in creating Instagram-worthy wedding stages and mandap designs. Their team of 30+ craftsmen can set up even the most elaborate designs overnight. Known for innovative use of flowers, draping, and ambient lighting, they have been featured in several wedding magazines.",
    city: "Mumbai",
    area: "Andheri",
    priceMin: 75000,
    priceMax: 800000,
    priceUnit: "per event",
    rating: 4.7,
    reviewCount: 312,
    tags: ["Modern", "Stage Design", "Fresh Flowers", "Magazine Featured"],
    featured: true,
    verified: true,
    experience: 18,
    bookings: 1500,
    availability: true,
  },
  {
    id: "v-9",
    name: "Pushpa Tent & Light",
    slug: "pushpa-tent-light",
    category: "Tent & Decoration",
    categorySlug: "tent-decoration",
    subcategory: "Tent Setup",
    description: "Reliable tent, shamiyana, and lighting solutions for outdoor weddings.",
    longDescription: "Pushpa Tent & Light provides end-to-end outdoor wedding infrastructure including waterproof shamiyanas, elegant tents, complete seating arrangements, lighting grids, and flooring. Their quick setup team has handled 3000+ events across North India. Ideal for farmhouse and lawn weddings.",
    city: "Lucknow",
    area: "Gomti Nagar",
    priceMin: 25000,
    priceMax: 200000,
    priceUnit: "per event",
    rating: 4.5,
    reviewCount: 678,
    tags: ["Outdoor", "Shamiyana", "Lighting", "Seating"],
    featured: false,
    verified: true,
    experience: 30,
    bookings: 3200,
    availability: true,
  },
  {
    id: "v-10",
    name: "Floral Fantasy Decor",
    slug: "floral-fantasy-decor",
    category: "Tent & Decoration",
    categorySlug: "tent-decoration",
    subcategory: "Floral Decoration",
    description: "Premium floral wedding decorations with imported and exotic flowers.",
    longDescription: "Floral Fantasy Decor creates magical wedding environments using exotic flowers and innovative floral installations. From cascading orchid mandaps to rose petal pathways and jasmine chandeliers, their designs are pure art. They source premium flowers from across the world and have a cold storage facility to ensure freshness.",
    city: "Bangalore",
    area: "Indiranagar",
    priceMin: 100000,
    priceMax: 1000000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 198,
    tags: ["Premium", "Exotic Flowers", "Luxury", "Destination"],
    featured: true,
    verified: true,
    experience: 12,
    bookings: 480,
    availability: true,
  },
  {
    id: "v-11",
    name: "Anand Light & Decor",
    slug: "anand-light-decor",
    category: "Tent & Decoration",
    categorySlug: "tent-decoration",
    subcategory: "Lighting",
    description: "Specialty wedding lighting including fairy lights, chandeliers, and LED shows.",
    longDescription: "Anand Light & Decor transforms wedding venues with magical lighting solutions. From fairy light canopies to crystal chandelier installations, synchronized LED dance floors, and dramatic uplighting, they create unforgettable atmospheres. Also offer fireworks and sparkler arrangements for the vidaai and reception.",
    city: "Jaipur",
    area: "MI Road",
    priceMin: 30000,
    priceMax: 300000,
    priceUnit: "per event",
    rating: 4.6,
    reviewCount: 234,
    tags: ["Lighting", "LED", "Fairy Lights", "Fireworks"],
    featured: false,
    verified: true,
    experience: 15,
    bookings: 890,
    availability: true,
  },

  // --- Catering / Halwai ---
  {
    id: "v-12",
    name: "Sharma Ji Ka Dhaba Catering",
    slug: "sharma-ji-ka-dhaba-catering",
    category: "Catering / Halwai",
    categorySlug: "catering-halwai",
    subcategory: "Veg Catering",
    description: "Authentic North Indian vegetarian wedding feast with 100+ dishes.",
    longDescription: "Sharma Ji Ka Dhaba Catering has been serving unforgettable vegetarian wedding feasts since 1985. With a menu of 100+ dishes spanning paneer specialities, dal makhani, biryani, live chaat counters, and their legendary gulab jamun, they feed anywhere from 200 to 10,000 guests. Their team of 50 cooks ensures consistent quality across massive events.",
    city: "Delhi",
    area: "Lajpat Nagar",
    priceMin: 800,
    priceMax: 2500,
    priceUnit: "per plate",
    rating: 4.8,
    reviewCount: 876,
    tags: ["Pure Veg", "North Indian", "Live Counters", "Bulk Catering"],
    featured: true,
    verified: true,
    experience: 38,
    bookings: 4500,
    availability: true,
  },
  {
    id: "v-13",
    name: "Mughlai Dawat Caterers",
    slug: "mughlai-dawat-caterers",
    category: "Catering / Halwai",
    categorySlug: "catering-halwai",
    subcategory: "Non-Veg Catering",
    description: "Legendary Mughlai cuisine with succulent kebabs and aromatic biryanis.",
    longDescription: "Mughlai Dawat Caterers are the undisputed kings of non-vegetarian wedding feasts in Lucknow. Their signature Lucknowi biryani, galouti kebabs, nihari, and shahi tukda have been the highlight of thousands of Nikah and Walima receptions. Run by the 4th generation of master chefs, they bring the royal kitchens of Awadh to your wedding.",
    city: "Lucknow",
    area: "Aminabad",
    priceMin: 1000,
    priceMax: 3500,
    priceUnit: "per plate",
    rating: 4.9,
    reviewCount: 567,
    tags: ["Mughlai", "Non-Veg", "Biryani", "Kebabs"],
    featured: true,
    verified: true,
    experience: 45,
    bookings: 3800,
    availability: true,
  },
  {
    id: "v-14",
    name: "Annapurna Bhog Caterers",
    slug: "annapurna-bhog-caterers",
    category: "Catering / Halwai",
    categorySlug: "catering-halwai",
    subcategory: "South Indian Catering",
    description: "Traditional South Indian wedding feast with banana leaf service.",
    longDescription: "Annapurna Bhog Caterers specialize in authentic South Indian wedding cuisine served on traditional banana leaves. From elaborate Sadya to filter coffee stations, dosa counters, and Chettinad specials, they bring the flavors of South India to your wedding. Known for impeccable hygiene standards and beautiful serving presentations.",
    city: "Chennai",
    area: "T Nagar",
    priceMin: 600,
    priceMax: 2000,
    priceUnit: "per plate",
    rating: 4.7,
    reviewCount: 423,
    tags: ["South Indian", "Banana Leaf", "Sadya", "Filter Coffee"],
    featured: false,
    verified: true,
    experience: 22,
    bookings: 2100,
    availability: true,
  },
  {
    id: "v-15",
    name: "Gupta Sweets & Halwai",
    slug: "gupta-sweets-halwai",
    category: "Catering / Halwai",
    categorySlug: "catering-halwai",
    subcategory: "Sweets / Mithai",
    description: "Traditional Indian sweets, mithai boxes, and live sweet counters.",
    longDescription: "Gupta Sweets & Halwai is a household name in Jaipur for wedding sweets and mithai. From elaborate mithai gift boxes for the baarat to live jalebi and rabri counters at the reception, they handle all sweet needs. Their signature items include Ghewar, Mawa Kachori, and handcrafted designer mithai boxes.",
    city: "Jaipur",
    area: "Johari Bazaar",
    priceMin: 400,
    priceMax: 1200,
    priceUnit: "per kg",
    rating: 4.8,
    reviewCount: 789,
    tags: ["Mithai", "Gift Boxes", "Live Counters", "Ghewar"],
    featured: false,
    verified: true,
    experience: 50,
    bookings: 5200,
    availability: true,
  },
  {
    id: "v-16",
    name: "The Grand Kitchen",
    slug: "the-grand-kitchen",
    category: "Catering / Halwai",
    categorySlug: "catering-halwai",
    subcategory: "Multi-Cuisine Catering",
    description: "Luxury multi-cuisine catering with international food stations.",
    longDescription: "The Grand Kitchen brings a luxury dining experience to Indian weddings with their multi-cuisine approach. From sushi bars and pasta stations to tandoor counters and live grills, they offer a global food journey. Their executive chefs have trained at 5-star hotels and bring that level of presentation and quality to outdoor wedding venues.",
    city: "Mumbai",
    area: "Worli",
    priceMin: 2000,
    priceMax: 5000,
    priceUnit: "per plate",
    rating: 4.8,
    reviewCount: 234,
    tags: ["Multi-Cuisine", "Luxury", "Live Stations", "5-Star Quality"],
    featured: true,
    verified: true,
    experience: 15,
    bookings: 890,
    availability: true,
  },
  {
    id: "v-17",
    name: "Bengali Bhojan Caterers",
    slug: "bengali-bhojan-caterers",
    category: "Catering / Halwai",
    categorySlug: "catering-halwai",
    subcategory: "Bengali Catering",
    description: "Authentic Bengali wedding feast with fish curry, mishti doi, and rosogolla.",
    longDescription: "Bengali Bhojan Caterers serve the quintessential Bengali wedding feast with luchi-alur dom, kosha mangsho, chingri malaikari, and a spectacular mishti counter featuring handmade rosogolla, sandesh, and mishti doi. They have been the caterers of choice for Kolkata's elite Bengali weddings for over 30 years.",
    city: "Kolkata",
    area: "Ballygunge",
    priceMin: 700,
    priceMax: 2200,
    priceUnit: "per plate",
    rating: 4.7,
    reviewCount: 345,
    tags: ["Bengali", "Fish", "Mishti", "Traditional"],
    featured: false,
    verified: true,
    experience: 30,
    bookings: 2800,
    availability: true,
  },

  // --- Makeup Artist ---
  {
    id: "v-18",
    name: "Glamour by Neha",
    slug: "glamour-by-neha",
    category: "Makeup Artist",
    categorySlug: "makeup-artist",
    subcategory: "Bridal Makeup",
    description: "Celebrity bridal makeup artist with airbrush and HD techniques.",
    longDescription: "Neha is one of Delhi's most sought-after bridal makeup artists, known for her flawless airbrush technique and natural-looking HD makeup. She creates stunning looks that last through every ceremony, from the mehndi to the reception. With a team of 5 artists, she can also handle the bride's family and bridesmaids.",
    city: "Delhi",
    area: "South Extension",
    priceMin: 25000,
    priceMax: 80000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 456,
    tags: ["Airbrush", "HD Makeup", "Celebrity", "Bridal Package"],
    featured: true,
    verified: true,
    experience: 14,
    bookings: 1200,
    availability: true,
  },
  {
    id: "v-19",
    name: "Aisha Beauty Studio",
    slug: "aisha-beauty-studio",
    category: "Makeup Artist",
    categorySlug: "makeup-artist",
    subcategory: "Bridal Makeup",
    description: "Elegant bridal looks specializing in Muslim and South Indian brides.",
    longDescription: "Aisha Beauty Studio celebrates the diverse beauty of Indian brides. Specializing in Muslim bridal looks with heavy dupatta draping and South Indian brides with traditional jewellery styling, Aisha creates culturally authentic yet modern bridal appearances. She uses only premium international brands and offers pre-bridal skincare packages.",
    city: "Hyderabad",
    area: "Banjara Hills",
    priceMin: 15000,
    priceMax: 50000,
    priceUnit: "per event",
    rating: 4.8,
    reviewCount: 312,
    tags: ["Muslim Bridal", "South Indian", "Skincare", "Premium Brands"],
    featured: true,
    verified: true,
    experience: 10,
    bookings: 780,
    availability: true,
  },
  {
    id: "v-20",
    name: "Ritu's Makeover Studio",
    slug: "ritus-makeover-studio",
    category: "Makeup Artist",
    categorySlug: "makeup-artist",
    subcategory: "Family Makeup",
    description: "Affordable family and guest makeup packages for wedding functions.",
    longDescription: "Ritu's Makeover Studio offers comprehensive makeup packages for the entire wedding party. From the bride's mother to the bridesmaids, her team of 8 artists ensures everyone looks their best. Budget-friendly packages without compromising on quality, using professional-grade products that last all day.",
    city: "Jaipur",
    area: "C-Scheme",
    priceMin: 5000,
    priceMax: 25000,
    priceUnit: "per person",
    rating: 4.5,
    reviewCount: 567,
    tags: ["Family Package", "Budget Friendly", "Team Available", "All Functions"],
    featured: false,
    verified: true,
    experience: 8,
    bookings: 1500,
    availability: true,
  },
  {
    id: "v-21",
    name: "MAC Pro Bridal Studio",
    slug: "mac-pro-bridal-studio",
    category: "Makeup Artist",
    categorySlug: "makeup-artist",
    subcategory: "Luxury Bridal",
    description: "Ultra-luxury bridal makeup with international products and techniques.",
    longDescription: "MAC Pro Bridal Studio offers the ultimate luxury bridal experience. Using exclusively MAC, Charlotte Tilbury, and Pat McGrath products, their artists create red-carpet-worthy looks. The package includes a pre-wedding trial, a dedicated stylist for all ceremonies, and a touch-up kit for the bride.",
    city: "Mumbai",
    area: "Juhu",
    priceMin: 50000,
    priceMax: 200000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 189,
    tags: ["Luxury", "MAC Products", "Celebrity Style", "Trial Included"],
    featured: true,
    verified: true,
    experience: 12,
    bookings: 450,
    availability: true,
  },
  {
    id: "v-22",
    name: "Sunita's Beauty Parlour",
    slug: "sunitas-beauty-parlour",
    category: "Makeup Artist",
    categorySlug: "makeup-artist",
    subcategory: "Traditional Makeup",
    description: "Traditional bridal makeup with expertise in Bengali and Marwari styles.",
    longDescription: "Sunita's Beauty Parlour has been creating traditional Indian bridal looks for 20 years. Specializing in Bengali bridal makeup with the signature red and white look, and Marwari bridal styles with heavy jewellery coordination. Sunita understands traditional aesthetics and creates timeless bridal looks that families love.",
    city: "Kolkata",
    area: "Park Street",
    priceMin: 8000,
    priceMax: 30000,
    priceUnit: "per event",
    rating: 4.6,
    reviewCount: 678,
    tags: ["Traditional", "Bengali Style", "Marwari", "Hair Styling"],
    featured: false,
    verified: true,
    experience: 20,
    bookings: 2200,
    availability: true,
  },

  // --- Photography & Video ---
  {
    id: "v-23",
    name: "PixelStory Studios",
    slug: "pixelstory-studios",
    category: "Photography & Video",
    categorySlug: "photography-video",
    subcategory: "Wedding Photography",
    description: "Award-winning wedding photography with a candid storytelling approach.",
    longDescription: "PixelStory Studios captures your wedding day as a beautiful visual narrative. Their candid photography style has won multiple awards at the Wedding Photographer Association of India. Using top-of-the-line Canon and Sony equipment, they deliver 1000+ edited photos and a cinematic highlight reel. Available for multi-day Indian wedding coverage.",
    city: "Mumbai",
    area: "Lower Parel",
    priceMin: 50000,
    priceMax: 300000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 567,
    tags: ["Candid", "Award Winning", "Cinematic", "Multi-Day"],
    featured: true,
    verified: true,
    experience: 10,
    bookings: 890,
    availability: true,
  },
  {
    id: "v-24",
    name: "DreamFrame Cinematics",
    slug: "dreamframe-cinematics",
    category: "Photography & Video",
    categorySlug: "photography-video",
    subcategory: "Wedding Videography",
    description: "Cinematic wedding films with drone shots and Bollywood-style edits.",
    longDescription: "DreamFrame Cinematics creates Hollywood-quality wedding films. Their team of cinematographers uses 4K cameras, drones, jibs, and steadicams to capture every moment in stunning detail. They offer same-day edit trailers, full-length wedding films, and Bollywood-style song sequences. Their films have gone viral on YouTube with millions of views.",
    city: "Delhi",
    area: "Connaught Place",
    priceMin: 75000,
    priceMax: 500000,
    priceUnit: "per event",
    rating: 4.8,
    reviewCount: 345,
    tags: ["Cinematic", "4K", "Drone", "Same Day Edit"],
    featured: true,
    verified: true,
    experience: 8,
    bookings: 650,
    availability: true,
  },
  {
    id: "v-25",
    name: "Snap Tales Photography",
    slug: "snap-tales-photography",
    category: "Photography & Video",
    categorySlug: "photography-video",
    subcategory: "Pre-Wedding Shoots",
    description: "Creative pre-wedding and couple photoshoots at exotic locations.",
    longDescription: "Snap Tales Photography is your go-to for stunning pre-wedding photoshoots. They scout unique locations across India - from Rajasthan's forts to Kerala's backwaters and Goa's beaches. Their creative direction ensures each couple's personality shines through. Packages include outfit changes, props, and professional editing.",
    city: "Jaipur",
    area: "Amer",
    priceMin: 25000,
    priceMax: 150000,
    priceUnit: "per shoot",
    rating: 4.7,
    reviewCount: 234,
    tags: ["Pre-Wedding", "Location Shoots", "Creative", "Couple Portraits"],
    featured: false,
    verified: true,
    experience: 6,
    bookings: 890,
    availability: true,
  },
  {
    id: "v-26",
    name: "FotoWale",
    slug: "fotowale",
    category: "Photography & Video",
    categorySlug: "photography-video",
    subcategory: "Budget Photography",
    description: "Professional wedding photography at affordable rates.",
    longDescription: "FotoWale makes professional wedding photography accessible to everyone. Their team of trained photographers delivers quality coverage of all wedding events including mehndi, sangeet, haldi, wedding ceremony, and reception. Budget-friendly packages with digital delivery and beautiful photo albums.",
    city: "Bangalore",
    area: "HSR Layout",
    priceMin: 15000,
    priceMax: 60000,
    priceUnit: "per event",
    rating: 4.5,
    reviewCount: 789,
    tags: ["Affordable", "All Events", "Digital Delivery", "Album"],
    featured: false,
    verified: true,
    experience: 5,
    bookings: 2100,
    availability: true,
  },
  {
    id: "v-27",
    name: "Shutter Singh",
    slug: "shutter-singh",
    category: "Photography & Video",
    categorySlug: "photography-video",
    subcategory: "Traditional Photography",
    description: "Traditional and candid photography with beautiful wedding albums.",
    longDescription: "Shutter Singh offers a perfect blend of traditional posed photography and modern candid shots. Known for their beautifully designed premium wedding albums with leather covers and lay-flat pages. They also provide a photo booth setup for reception parties with fun props and instant prints.",
    city: "Chandigarh",
    area: "Sector 17",
    priceMin: 30000,
    priceMax: 120000,
    priceUnit: "per event",
    rating: 4.6,
    reviewCount: 456,
    tags: ["Traditional", "Albums", "Photo Booth", "Instant Prints"],
    featured: false,
    verified: true,
    experience: 12,
    bookings: 1500,
    availability: true,
  },
  {
    id: "v-28",
    name: "WedFilms India",
    slug: "wedfilms-india",
    category: "Photography & Video",
    categorySlug: "photography-video",
    subcategory: "Photo + Video Combo",
    description: "Complete photo and video packages for destination weddings.",
    longDescription: "WedFilms India offers comprehensive photography and videography packages designed for destination weddings across India. Their 8-member crew handles everything from pre-wedding shoots to post-wedding brunch coverage. Known for their quick turnaround - highlights delivered within 48 hours and full package within 4 weeks.",
    city: "Udaipur",
    area: "Lake Palace Road",
    priceMin: 100000,
    priceMax: 600000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 178,
    tags: ["Destination", "Photo+Video", "Quick Delivery", "Full Coverage"],
    featured: true,
    verified: true,
    experience: 9,
    bookings: 340,
    availability: true,
  },

  // --- Wedding Venues ---
  {
    id: "v-29",
    name: "The Grand Palace Banquets",
    slug: "the-grand-palace-banquets",
    category: "Wedding Venues",
    categorySlug: "wedding-venues",
    subcategory: "Banquet Hall",
    description: "Luxury banquet hall with capacity for 2000+ guests and in-house catering.",
    longDescription: "The Grand Palace Banquets is one of Delhi's premier wedding venues, offering three magnificent halls accommodating 500 to 2000+ guests. With stunning crystal chandeliers, imported marble flooring, and a dedicated wedding team, they provide a complete wedding experience. In-house catering with 200+ menu options, ample parking for 500 cars, and bridal suites included.",
    city: "Delhi",
    area: "GT Karnal Road",
    priceMin: 150000,
    priceMax: 1500000,
    priceUnit: "per event",
    rating: 4.7,
    reviewCount: 456,
    tags: ["Luxury", "2000+ Capacity", "In-House Catering", "Parking"],
    featured: true,
    verified: true,
    experience: 20,
    bookings: 3500,
    availability: true,
  },
  {
    id: "v-30",
    name: "Lakeside Heritage Resort",
    slug: "lakeside-heritage-resort",
    category: "Wedding Venues",
    categorySlug: "wedding-venues",
    subcategory: "Heritage Property",
    description: "Stunning lakeside heritage property perfect for destination weddings.",
    longDescription: "Lakeside Heritage Resort in Udaipur offers a fairy-tale destination wedding experience. Set against the backdrop of the Aravalli hills and a pristine lake, this heritage property features open-air mandap areas, a royal dining hall, and beautifully landscaped gardens. Accommodation for 200+ guests in heritage-themed rooms and suites.",
    city: "Udaipur",
    area: "Fateh Sagar",
    priceMin: 500000,
    priceMax: 5000000,
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 234,
    tags: ["Heritage", "Lakeside", "Destination", "Accommodation"],
    featured: true,
    verified: true,
    experience: 15,
    bookings: 450,
    availability: true,
  },
  {
    id: "v-31",
    name: "Green Garden Lawns",
    slug: "green-garden-lawns",
    category: "Wedding Venues",
    categorySlug: "wedding-venues",
    subcategory: "Garden / Lawn",
    description: "Beautiful open-air garden venue for outdoor weddings and receptions.",
    longDescription: "Green Garden Lawns offers a lush 3-acre manicured garden perfect for outdoor Indian weddings. The venue features a permanent mandap structure, multiple lawn areas for different ceremonies, a built-in stage with lighting rig, and backup generators. Can accommodate up to 1500 guests with comfortable arrangements. External caterers allowed.",
    city: "Bangalore",
    area: "Whitefield",
    priceMin: 80000,
    priceMax: 400000,
    priceUnit: "per event",
    rating: 4.6,
    reviewCount: 567,
    tags: ["Outdoor", "Garden", "1500 Capacity", "External Caterers OK"],
    featured: false,
    verified: true,
    experience: 12,
    bookings: 1800,
    availability: true,
  },
  {
    id: "v-32",
    name: "Hotel Maharaja Residency",
    slug: "hotel-maharaja-residency",
    category: "Wedding Venues",
    categorySlug: "wedding-venues",
    subcategory: "Hotel Venue",
    description: "5-star hotel wedding venue with world-class amenities and service.",
    longDescription: "Hotel Maharaja Residency offers the ultimate luxury hotel wedding experience. With a grand ballroom seating 800, a poolside cocktail area, and rooftop reception space, every ceremony gets its own spectacular setting. 5-star in-house catering, valet parking, 150+ rooms for guests, spa and salon services, and a dedicated wedding planner are all included.",
    city: "Mumbai",
    area: "Marine Drive",
    priceMin: 300000,
    priceMax: 3000000,
    priceUnit: "per event",
    rating: 4.8,
    reviewCount: 312,
    tags: ["5-Star", "Multiple Spaces", "Full Service", "Sea View"],
    featured: true,
    verified: true,
    experience: 25,
    bookings: 1200,
    availability: true,
  },
  {
    id: "v-33",
    name: "Rajwada Marriage Hall",
    slug: "rajwada-marriage-hall",
    category: "Wedding Venues",
    categorySlug: "wedding-venues",
    subcategory: "Marriage Hall",
    description: "Affordable marriage hall with AC and non-AC options.",
    longDescription: "Rajwada Marriage Hall is the trusted choice for families looking for a quality yet affordable venue. With both AC and non-AC halls ranging from 200 to 800 capacity, they cater to weddings of all sizes. Located in a convenient central location with easy access, ample parking, and the flexibility to bring your own caterer and decorator.",
    city: "Lucknow",
    area: "Alambagh",
    priceMin: 30000,
    priceMax: 150000,
    priceUnit: "per event",
    rating: 4.4,
    reviewCount: 890,
    tags: ["Affordable", "AC & Non-AC", "Central Location", "Flexible"],
    featured: false,
    verified: true,
    experience: 18,
    bookings: 4200,
    availability: true,
  },

  // --- Event Managers ---
  {
    id: "v-34",
    name: "WedPlan India",
    slug: "wedplan-india",
    category: "Event Managers",
    categorySlug: "event-managers",
    subcategory: "Full Wedding Planning",
    description: "End-to-end wedding planning with vendor management and budget tracking.",
    longDescription: "WedPlan India takes the stress out of wedding planning with their comprehensive end-to-end service. From the first meeting to the vidaai, their team of experienced planners handles venue selection, vendor coordination, budget management, timeline creation, guest management, and day-of execution. They have a network of 500+ verified vendors across India.",
    city: "Delhi",
    area: "Hauz Khas",
    priceMin: 200000,
    priceMax: 2000000,
    priceUnit: "per wedding",
    rating: 4.9,
    reviewCount: 234,
    tags: ["Full Planning", "Vendor Network", "Budget Management", "500+ Vendors"],
    featured: true,
    verified: true,
    experience: 12,
    bookings: 450,
    availability: true,
  },
  {
    id: "v-35",
    name: "Shagun Events",
    slug: "shagun-events",
    category: "Event Managers",
    categorySlug: "event-managers",
    subcategory: "Day-of Coordination",
    description: "Professional day-of coordination ensuring smooth execution of your wedding.",
    longDescription: "Shagun Events specializes in day-of wedding coordination for families who plan their own wedding but need professional execution. Their team arrives the day before to coordinate with all vendors, manage timelines, handle emergencies, and ensure every ceremony runs smoothly. Perfect for families who want control over planning but peace of mind on the big day.",
    city: "Mumbai",
    area: "Powai",
    priceMin: 50000,
    priceMax: 200000,
    priceUnit: "per event",
    rating: 4.7,
    reviewCount: 345,
    tags: ["Day-of", "Coordination", "Vendor Management", "Timeline"],
    featured: false,
    verified: true,
    experience: 8,
    bookings: 890,
    availability: true,
  },
  {
    id: "v-36",
    name: "Royal Destination Weddings",
    slug: "royal-destination-weddings",
    category: "Event Managers",
    categorySlug: "event-managers",
    subcategory: "Destination Weddings",
    description: "Specialist in luxury destination weddings across Rajasthan and Goa.",
    longDescription: "Royal Destination Weddings creates magical wedding experiences at India's most stunning destinations. From palace weddings in Udaipur and Jaipur to beach celebrations in Goa and backwater ceremonies in Kerala, they handle everything including guest travel, accommodation, local permits, and multi-day event coordination. Their signature royal Rajasthani wedding experience is unmatched.",
    city: "Jaipur",
    area: "Civil Lines",
    priceMin: 500000,
    priceMax: 10000000,
    priceUnit: "per wedding",
    rating: 4.9,
    reviewCount: 178,
    tags: ["Destination", "Rajasthan", "Goa", "Palace Weddings"],
    featured: true,
    verified: true,
    experience: 15,
    bookings: 280,
    availability: true,
  },
  {
    id: "v-37",
    name: "Budget Shaadi Planners",
    slug: "budget-shaadi-planners",
    category: "Event Managers",
    categorySlug: "event-managers",
    subcategory: "Budget Planning",
    description: "Quality wedding planning that respects your budget without compromises.",
    longDescription: "Budget Shaadi Planners prove that a beautiful Indian wedding doesn't need to break the bank. They specialize in maximizing impact within budget constraints. Their team negotiates the best rates with vendors, suggests creative cost-saving alternatives, and ensures every rupee is well spent. They have successfully planned stunning weddings starting from just 3 lakhs.",
    city: "Bangalore",
    area: "BTM Layout",
    priceMin: 30000,
    priceMax: 150000,
    priceUnit: "per wedding",
    rating: 4.6,
    reviewCount: 567,
    tags: ["Budget", "Cost Effective", "Full Planning", "Value"],
    featured: false,
    verified: true,
    experience: 6,
    bookings: 1200,
    availability: true,
  },
  {
    id: "v-38",
    name: "Celebrations by Kavya",
    slug: "celebrations-by-kavya",
    category: "Event Managers",
    categorySlug: "event-managers",
    subcategory: "Luxury Planning",
    description: "Ultra-luxury wedding planning for the most discerning families.",
    longDescription: "Celebrations by Kavya is the name behind some of India's most talked-about celebrity and billionaire weddings. Kavya and her team of 20 planners deliver impossibly beautiful, flawlessly executed weddings that make headlines. From flying in international performers to creating custom wedding apps for guests and managing security for high-profile families, no detail is too small.",
    city: "Mumbai",
    area: "Breach Candy",
    priceMin: 1000000,
    priceMax: 50000000,
    priceUnit: "per wedding",
    rating: 5.0,
    reviewCount: 89,
    tags: ["Ultra Luxury", "Celebrity", "International", "High Profile"],
    featured: true,
    verified: true,
    experience: 18,
    bookings: 120,
    availability: true,
  },
];

export const vendors: Vendor[] = _vendorsLegacy.map((v) => ({
  ...v,
  vendorType: null,
  coverImageUrl: null,
  logoUrl: null,
}));
